<script setup lang="ts">
import { h, ref, onMounted } from 'vue'
import {
  NCard, NButton, NSpace, NInput, NAlert, NTag, NDataTable, NModal, NText, useMessage,
} from 'naive-ui'
import type { DataTableColumns } from 'naive-ui'
import { api, ApiError } from '../api/client'
import type { Peer, ChainKey } from '../api/client'

const message = useMessage()
const peers = ref<Peer[]>([])
const loading = ref(false)

// add peer
const newName = ref('')
const newKey = ref('')
const adding = ref(false)

// generated key modal
const keyModal = ref(false)
const generated = ref<ChainKey | null>(null)
const generating = ref(false)

const columns: DataTableColumns<Peer> = [
  { title: 'Name', key: 'name' },
  { title: 'Local SOCKS5', key: 'socks5Port', render: (p) => `127.0.0.1:${p.socks5Port}` },
  {
    title: 'Status',
    key: 'status',
    render: (p) =>
      h(NTag, { type: p.running ? 'success' : 'warning', size: 'small' }, { default: () => (p.running ? 'connected' : 'starting') }),
  },
  {
    title: '',
    key: 'actions',
    render: (p) =>
      h(NButton, { size: 'small', type: 'error', quaternary: true, onClick: () => remove(p.name) }, { default: () => 'Remove' }),
  },
]

async function load() {
  loading.value = true
  try {
    peers.value = await api.get<Peer[]>('/api/chain')
  } catch (e) {
    message.error(e instanceof ApiError ? e.message : 'Failed to load peers')
  } finally {
    loading.value = false
  }
}

async function addPeer() {
  if (!newName.value.trim() || !newKey.value.trim()) {
    message.error('Name and key are required')
    return
  }
  adding.value = true
  try {
    peers.value = await api.post<Peer[]>('/api/chain', { name: newName.value.trim(), key: newKey.value.trim() })
    newName.value = ''
    newKey.value = ''
    message.success('Peer connected. It is now available as a proxy in Outbounds rules.')
  } catch (e) {
    message.error(e instanceof ApiError ? e.message : 'Failed to add peer')
  } finally {
    adding.value = false
  }
}

async function remove(name: string) {
  try {
    peers.value = await api.del<Peer[]>(`/api/chain/${encodeURIComponent(name)}`)
  } catch (e) {
    message.error(e instanceof ApiError ? e.message : 'Failed to remove peer')
  }
}

async function generateKey() {
  generating.value = true
  try {
    generated.value = await api.post<ChainKey>('/api/chain/key', {})
    keyModal.value = true
  } catch (e) {
    message.error(e instanceof ApiError ? e.message : 'Failed to generate key')
  } finally {
    generating.value = false
  }
}

function copy(text: string) {
  navigator.clipboard.writeText(text).then(
    () => message.success('Copied'),
    () => message.error('Copy failed'),
  )
}

onMounted(load)
</script>

<template>
  <h2 class="page-title">Chain</h2>
  <n-space vertical :size="16">
    <n-card title="Upstream panels">
      <n-alert type="info" :show-icon="false" style="margin-bottom: 12px">
        Route this panel's egress through another mieru panel. Paste a peer key generated by the other
        panel; this panel runs a client to it and exposes it as a proxy you can reference in
        <b>Outbounds</b> rules (e.g. send everything, or only certain traffic, through it).
      </n-alert>
      <n-space align="center" style="margin-bottom: 14px">
        <n-input v-model:value="newName" placeholder="name (e.g. exitNode)" style="width: 180px" />
        <n-input v-model:value="newKey" placeholder="paste peer key (mieru://...)" style="width: 380px" />
        <n-button type="primary" :loading="adding" @click="addPeer">Connect</n-button>
      </n-space>
      <n-data-table :columns="columns" :data="peers" :loading="loading" :row-key="(p: Peer) => p.name" size="small" />
    </n-card>

    <n-card title="Use this panel as an upstream">
      <template #header-extra>
        <n-button :loading="generating" @click="generateKey">Generate peer key</n-button>
      </template>
      <n-text depth="3" style="font-size: 13px">
        Generate a key and paste it into another panel's <b>Upstream panels</b> to let it route through
        this server. The key contains credentials, so share it privately.
      </n-text>
    </n-card>

    <n-modal v-model:show="keyModal" preset="card" title="Peer key" style="width: 520px">
      <n-space v-if="generated" vertical>
        <n-text depth="3" style="font-size: 12px">
          Paste this into the other panel. User <b>{{ generated.name }}</b> was created here for the chain.
          Treat it as a secret.
        </n-text>
        <n-input :value="generated.key" type="textarea" readonly :autosize="{ minRows: 3, maxRows: 6 }" />
        <n-button size="small" @click="copy(generated.key)">Copy key</n-button>
      </n-space>
    </n-modal>
  </n-space>
</template>
